language: r
warnings_are_errors: true
sudo: required

os:
  - linux
  - osx

apt_packages:
 - python-dev
 - python

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
