language: r
warnings_are_errors: true
sudo: required

r_packages:
  - covr

os:
  - linux
  - osx

apt_packages:
 - python-dev
 - python

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'library("covr");codecov()'
